# Generated by Django 4.2.7 on 2025-07-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apontamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_poste_tubo", models.CharField(max_length=50)),
                (
                    "diametro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("inicio_processo", models.DateTimeField()),
                ("fim_processo", models.DateTimeField(blank=True, null=True)),
                (
                    "tempo_real",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Em minutos",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tempo_padrao",
                    models.DecimalField(
                        decimal_places=2, help_text="Em minutos", max_digits=6
                    ),
                ),
                (
                    "eficiencia_calculada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "apontamento",
                "ordering": ["-inicio_processo"],
            },
        ),
        migrations.CreateModel(
            name="Componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tempo_padrao",
                    models.DecimalField(
                        decimal_places=2, help_text="Tempo em minutos", max_digits=6
                    ),
                ),
                ("considera_diametro", models.BooleanField(default=False)),
                (
                    "formula_calculo",
                    models.TextField(
                        blank=True,
                        help_text="Fórmula para calcular tempo baseado no diâmetro",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "componente",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem_exibicao", models.IntegerField(default=0)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "modulo",
                "ordering": ["ordem_exibicao", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_prevista", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "pedido",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="TipoParada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("manutencao", "Manutenção"),
                            ("qualidade", "Qualidade"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "penaliza_oee",
                    models.BooleanField(
                        default=True, help_text="Se deve ser considerado no cálculo OEE"
                    ),
                ),
                ("requer_senha_especial", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                ("cor_exibicao", models.CharField(default="#dc3545", max_length=7)),
            ],
            options={
                "db_table": "tipo_parada",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_turno", models.DateField()),
                ("inicio_turno", models.DateTimeField()),
                ("fim_turno", models.DateTimeField(blank=True, null=True)),
                (
                    "horas_disponiveis",
                    models.DecimalField(decimal_places=2, default=8, max_digits=4),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("finalizado", "Finalizado")],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
                    ),
                ),
            ],
            options={
                "db_table": "turno",
                "ordering": ["-data_turno", "-inicio_turno"],
                "unique_together": {("soldador", "data_turno", "inicio_turno")},
            },
        ),
        migrations.CreateModel(
            name="Parada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField(blank=True, null=True)),
                (
                    "duracao_minutos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("motivo_detalhado", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "apontamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.apontamento",
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
                    ),
                ),
                (
                    "tipo_parada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.tipoparada",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.turno",
                    ),
                ),
                (
                    "usuario_autorizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "parada",
                "ordering": ["-inicio"],
            },
        ),
        migrations.AddField(
            model_name="apontamento",
            name="componente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.componente"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.modulo"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.pedido"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="soldador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="soldagem.turno",
            ),
        ),
    ]
