# Generated by Django 4.2.7 on 2025-07-07 11:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("analista", "Analista"),
                            ("qualidade", "Qualidade"),
                            ("manutencao", "Manutenção"),
                            ("soldador", "Soldador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultimo_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo_dado",
                    models.CharField(
                        choices=[
                            ("string", "Texto"),
                            ("integer", "Número Inteiro"),
                            ("float", "Número Decimal"),
                            ("boolean", "Verdadeiro/Falso"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Configurações do Sistema",
                "db_table": "configuracao_sistema",
            },
        ),
        migrations.CreateModel(
            name="HoraTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "horas_disponiveis",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "dias_semana",
                    models.JSONField(
                        default=list,
                        help_text="Lista com dias da semana [0-6, 0=Segunda]",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Horas de Trabalho",
                "db_table": "hora_trabalho",
            },
        ),
        migrations.CreateModel(
            name="LogSincronizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispositivo_id", models.CharField(max_length=100)),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("sync", "Sincronização"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tabela", models.CharField(max_length=100)),
                ("registros_afetados", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                            ("pendente", "Pendente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mensagem_erro", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Logs de Sincronização",
                "db_table": "log_sincronizacao",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Soldador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "senha_simplificada",
                    models.CharField(
                        help_text="Senha para login rápido", max_length=20
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldador_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Soldadores",
                "db_table": "soldador",
            },
        ),
        migrations.CreateModel(
            name="SessaoOffline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispositivo_id", models.CharField(max_length=100, unique=True)),
                ("dados_cache", models.JSONField(default=dict)),
                ("ultimo_sync", models.DateTimeField(auto_now=True)),
                ("status_conexao", models.BooleanField(default=True)),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sessões Offline",
                "db_table": "sessao_offline",
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=255)),
                ("tabela_afetada", models.CharField(blank=True, max_length=100)),
                ("registro_id", models.IntegerField(blank=True, null=True)),
                ("dados_antes", models.JSONField(blank=True, null=True)),
                ("dados_depois", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "log_auditoria",
                "ordering": ["-timestamp"],
            },
        ),
    ]
