# Generated by Django 4.2.7 on 2025-07-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("soldagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDefeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("cor_exibicao", models.CharField(default="#ffc107", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Tipos de Defeito",
                "db_table": "tipo_defeito",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Defeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tamanho do defeito em mm",
                        max_digits=8,
                    ),
                ),
                (
                    "area_defeito",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Área calculada em mm²",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("data_deteccao", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "apontamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.apontamento",
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
                    ),
                ),
                (
                    "tipo_defeito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qualidade.tipodefeito",
                    ),
                ),
                (
                    "usuario_qualidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defeitos_detectados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "defeito",
                "ordering": ["-data_deteccao"],
            },
        ),
        migrations.CreateModel(
            name="CalculoOEE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_calculo", models.DateField()),
                ("periodo_inicio", models.DateTimeField()),
                ("periodo_fim", models.DateTimeField()),
                (
                    "utilizacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "eficiencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "qualidade",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "oee_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "horas_trabalhadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "horas_disponiveis",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "tempo_paradas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "tempo_produtivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "tempo_padrao_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("total_pecas", models.IntegerField(default=0)),
                ("pecas_com_defeito", models.IntegerField(default=0)),
                (
                    "total_defeitos_mm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("timestamp_calculo", models.DateTimeField(auto_now=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.modulo",
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.soldador",
                    ),
                ),
            ],
            options={
                "db_table": "calculo_oee",
                "ordering": ["-data_calculo", "-timestamp_calculo"],
                "unique_together": {
                    ("soldador", "modulo", "data_calculo", "periodo_inicio")
                },
            },
        ),
    ]
